# Generated by Django 3.2.12 on 2022-05-31 00:12

import aurora_etc.comb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aurora_Article_Comment_Model',
            fields=[
                ('comb', models.CharField(default=aurora_etc.comb.Aurora_Comb_UUID.CombID, max_length=32, primary_key=True, serialize=False)),
                ('prefer', models.IntegerField(default=0)),
                ('comment_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('comment_create_time', models.DateTimeField(auto_now_add=True)),
                ('comment_content', models.CharField(max_length=3000, null=True)),
                ('comment_report', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'aurora_article_comment',
                'ordering': ['comment_create_time'],
            },
        ),
        migrations.CreateModel(
            name='Aurora_Article_Model',
            fields=[
                ('comb', models.CharField(default=aurora_etc.comb.Aurora_Comb_UUID.CombID, max_length=32, primary_key=True, serialize=False)),
                ('article_type', models.IntegerField(default=0)),
                ('article_sign', models.IntegerField(default=0)),
                ('article_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('article_create_time', models.DateTimeField(auto_now_add=True)),
                ('article_last_update_time', models.DateTimeField(auto_now=True)),
                ('article_img_list', models.CharField(default=None, max_length=1000, null=True)),
                ('article_title', models.CharField(max_length=100, null=True)),
                ('article_content', models.CharField(max_length=10000)),
            ],
            options={
                'db_table': 'aurora_article',
                'ordering': ['-article_last_update_time', '-article_create_time'],
            },
        ),
        migrations.CreateModel(
            name='Aurora_Group_Model',
            fields=[
                ('comb', models.CharField(default=aurora_etc.comb.Aurora_Comb_UUID.CombID, max_length=32, primary_key=True, serialize=False)),
                ('group_img', models.CharField(default='', max_length=100)),
                ('group_date_create', models.DateTimeField(auto_now_add=True)),
                ('group_member', models.IntegerField(default=0)),
                ('group_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('group_member_name', models.CharField(default='个用户', max_length=10)),
                ('group_title', models.CharField(max_length=40, unique=True)),
                ('group_report', models.CharField(default='', max_length=200)),
                ('group_introduction', models.CharField(default='', max_length=500)),
                ('group_color', models.CharField(default='#FFAB1A', max_length=10)),
                ('group_join_type', models.IntegerField(default=3)),
                ('group_join_type_content', models.CharField(default='', max_length=20)),
            ],
            options={
                'db_table': 'aurora_group',
            },
        ),
        migrations.CreateModel(
            name='Aurora_M2M_Article_Summary_Model',
            fields=[
                ('comb', models.CharField(default=aurora_etc.comb.Aurora_Comb_UUID.CombID, max_length=32, primary_key=True, serialize=False)),
                ('desc', models.CharField(default='', max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('m2m_article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aurora_main.aurora_article_model')),
            ],
            options={
                'db_table': 'aurora_m2m_article_summary',
            },
        ),
        migrations.CreateModel(
            name='Aurora_M2M_User_Follow_Summary_Model',
            fields=[
                ('comb', models.CharField(default=aurora_etc.comb.Aurora_Comb_UUID.CombID, max_length=32, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'aurora_m2m_user_follow_summary',
            },
        ),
        migrations.CreateModel(
            name='Aurora_M2M_User_Group_Model',
            fields=[
                ('comb', models.CharField(default=aurora_etc.comb.Aurora_Comb_UUID.CombID, max_length=32, primary_key=True, serialize=False)),
                ('m2m_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aurora_main.aurora_group_model')),
            ],
            options={
                'db_table': 'aurora_m2m_user_group',
            },
        ),
        migrations.CreateModel(
            name='Aurora_M2M_User_User_Follow_Model',
            fields=[
                ('comb', models.CharField(default=aurora_etc.comb.Aurora_Comb_UUID.CombID, max_length=32, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'aurora_m2m_user_user_follow',
            },
        ),
        migrations.CreateModel(
            name='Aurora_Meta_Model',
            fields=[
                ('key', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'aurora_meta',
            },
        ),
        migrations.CreateModel(
            name='Aurora_Summary_Model',
            fields=[
                ('comb', models.CharField(default=aurora_etc.comb.Aurora_Comb_UUID.CombID, max_length=32, primary_key=True, serialize=False)),
                ('summary_create_time', models.DateTimeField(auto_now_add=True)),
                ('summary_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('summary_title', models.CharField(max_length=100)),
                ('summary_pic', models.CharField(default='', max_length=100)),
                ('summary_is_private', models.BooleanField(default=True)),
                ('summary_keyword', models.CharField(max_length=50)),
                ('summary_describe', models.CharField(max_length=200)),
                ('summary_type', models.IntegerField(default=0)),
                ('m2m_article_summary', models.ManyToManyField(through='aurora_main.Aurora_M2M_Article_Summary_Model', to='aurora_main.Aurora_Article_Model')),
            ],
            options={
                'db_table': 'aurora_summary',
            },
        ),
        migrations.CreateModel(
            name='Aurora_User_Model',
            fields=[
                ('comb', models.CharField(default=aurora_etc.comb.Aurora_Comb_UUID.CombID, max_length=32, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('himg', models.CharField(default='', max_length=100)),
                ('bimg', models.CharField(default='', max_length=100)),
                ('ban', models.BooleanField(default=False)),
                ('user_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('user_login_name', models.CharField(default=None, max_length=30)),
                ('user_login_pwd', models.CharField(default=None, max_length=32)),
                ('user_login_salt', models.CharField(default='sd4fds89f', max_length=10)),
                ('user_date_create', models.DateTimeField(auto_now_add=True)),
                ('user_signature', models.CharField(default='她什么都没说哦。', max_length=40)),
                ('user_setting_allow_follow_explore', models.BooleanField(default=True)),
                ('digit_following', models.IntegerField(default=0)),
                ('digit_followed', models.IntegerField(default=0)),
                ('digit_article', models.IntegerField(default=0)),
                ('digit_group', models.IntegerField(default=0)),
                ('digit_last_up', models.DateTimeField(null=True)),
                ('m2m_follow', models.ManyToManyField(through='aurora_main.Aurora_M2M_User_User_Follow_Model', to='aurora_main.Aurora_User_Model')),
                ('m2m_user_group', models.ManyToManyField(through='aurora_main.Aurora_M2M_User_Group_Model', to='aurora_main.Aurora_Group_Model')),
            ],
            options={
                'db_table': 'aurora_user',
            },
        ),
        migrations.CreateModel(
            name='Aurora_Version_Model',
            fields=[
                ('version', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('force', models.BooleanField(default=False)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'aurora_version',
            },
        ),
        migrations.CreateModel(
            name='Aurora_Vote_Item_Model',
            fields=[
                ('comb', models.CharField(default=aurora_etc.comb.Aurora_Comb_UUID.CombID, max_length=32, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=40)),
                ('item_sum', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Aurora_Vote_Model',
            fields=[
                ('comb', models.CharField(default=aurora_etc.comb.Aurora_Comb_UUID.CombID, max_length=32, primary_key=True, serialize=False)),
                ('vote_name', models.CharField(default='投票', max_length=200)),
                ('vote_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aurora_main.aurora_article_model')),
            ],
        ),
        migrations.CreateModel(
            name='Aurora_Article_Info_Model',
            fields=[
                ('comb', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='info', serialize=False, to='aurora_main.aurora_article_model')),
                ('article_prefer', models.IntegerField(default=0)),
                ('article_up', models.IntegerField(default=0)),
                ('article_transmit', models.IntegerField(default=0, null=True)),
                ('article_star', models.IntegerField(default=0)),
                ('article_comment', models.IntegerField(default=0)),
                ('article_report', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'aurora_article_info',
            },
        ),
        migrations.CreateModel(
            name='Aurora_Summary_Info_Model',
            fields=[
                ('comb', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='aurora_main.aurora_summary_model')),
                ('summary_follow', models.IntegerField(default=0)),
                ('summary_dict', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'aurora_summary_info',
            },
        ),
        migrations.CreateModel(
            name='Aurora_Vote_Sub_Model',
            fields=[
                ('comb', models.CharField(default=aurora_etc.comb.Aurora_Comb_UUID.CombID, max_length=32, primary_key=True, serialize=False)),
                ('sub_item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aurora_main.aurora_vote_item_model')),
                ('sub_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aurora_main.aurora_user_model')),
                ('sub_vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aurora_main.aurora_vote_model')),
            ],
        ),
        migrations.AddField(
            model_name='aurora_vote_item_model',
            name='item_vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aurora_main.aurora_vote_model'),
        ),
        migrations.CreateModel(
            name='Aurora_Temp_M2M_Notice_Model',
            fields=[
                ('comb', models.CharField(default=aurora_etc.comb.Aurora_Comb_UUID.CombID, max_length=32, primary_key=True, serialize=False)),
                ('content', models.CharField(default='', max_length=100)),
                ('type', models.CharField(max_length=10, null=True)),
                ('type_id', models.CharField(max_length=60)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_to_user', to='aurora_main.aurora_user_model')),
            ],
            options={
                'db_table': 'aurora_temp_notice',
            },
        ),
        migrations.CreateModel(
            name='Aurora_Temp_M2M_Message_Model',
            fields=[
                ('comb', models.CharField(default=aurora_etc.comb.Aurora_Comb_UUID.CombID, max_length=32, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=2000)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('image', models.CharField(default='', max_length=100)),
                ('is_encrypt', models.BooleanField(default=False)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_message_from_user', to='aurora_main.aurora_user_model')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_message_to_user', to='aurora_main.aurora_user_model')),
            ],
            options={
                'db_table': 'aurora_temp_message',
            },
        ),
        migrations.CreateModel(
            name='Aurora_Temp_M2M_Comment_Notice_Model',
            fields=[
                ('comb', models.CharField(default=aurora_etc.comb.Aurora_Comb_UUID.CombID, max_length=32, primary_key=True, serialize=False)),
                ('type', models.CharField(default='帖子', max_length=5)),
                ('from_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aurora_main.aurora_article_comment_model')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aurora_main.aurora_user_model')),
            ],
            options={
                'db_table': 'aurora_temp_comment_notice',
            },
        ),
        migrations.AddField(
            model_name='aurora_summary_model',
            name='m2m_follow',
            field=models.ManyToManyField(related_name='f_follow_user', through='aurora_main.Aurora_M2M_User_Follow_Summary_Model', to='aurora_main.Aurora_User_Model'),
        ),
        migrations.AddField(
            model_name='aurora_summary_model',
            name='summary_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aurora_main.aurora_user_model'),
        ),
        migrations.AddField(
            model_name='aurora_m2m_user_user_follow_model',
            name='m2m_be_followed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_followed_user', to='aurora_main.aurora_user_model'),
        ),
        migrations.AddField(
            model_name='aurora_m2m_user_user_follow_model',
            name='m2m_following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_following_user', to='aurora_main.aurora_user_model'),
        ),
        migrations.CreateModel(
            name='Aurora_M2M_User_User_Block_Model',
            fields=[
                ('comb', models.CharField(default=aurora_etc.comb.Aurora_Comb_UUID.CombID, max_length=32, primary_key=True, serialize=False)),
                ('m2m_be_blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_blocked_user', to='aurora_main.aurora_user_model')),
                ('m2m_blocking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_blocking_user', to='aurora_main.aurora_user_model')),
            ],
            options={
                'db_table': 'aurora_m2m_user_user_block',
            },
        ),
        migrations.AddField(
            model_name='aurora_m2m_user_group_model',
            name='m2m_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aurora_main.aurora_user_model'),
        ),
        migrations.CreateModel(
            name='Aurora_M2M_User_Group_Block_Model',
            fields=[
                ('comb', models.CharField(default=aurora_etc.comb.Aurora_Comb_UUID.CombID, max_length=32, primary_key=True, serialize=False)),
                ('m2m_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_with_group', to='aurora_main.aurora_group_model')),
                ('m2m_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_with_user', to='aurora_main.aurora_user_model')),
            ],
            options={
                'db_table': 'aurora_user_group_block',
            },
        ),
        migrations.AddField(
            model_name='aurora_m2m_user_follow_summary_model',
            name='m2m_summary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aurora_main.aurora_summary_model'),
        ),
        migrations.AddField(
            model_name='aurora_m2m_user_follow_summary_model',
            name='m2m_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aurora_main.aurora_user_model'),
        ),
        migrations.CreateModel(
            name='Aurora_M2M_Report_Log_Model',
            fields=[
                ('comb', models.CharField(default=aurora_etc.comb.Aurora_Comb_UUID.CombID, max_length=32, primary_key=True, serialize=False)),
                ('with_id', models.CharField(max_length=40)),
                ('with_type', models.CharField(max_length=5)),
                ('with_reason', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('with_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_with_group', to='aurora_main.aurora_group_model')),
                ('with_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_with_user', to='aurora_main.aurora_user_model')),
            ],
            options={
                'db_table': 'aurora_report_log',
            },
        ),
        migrations.CreateModel(
            name='Aurora_M2M_Prefer_Comment_Model',
            fields=[
                ('comb', models.CharField(default=aurora_etc.comb.Aurora_Comb_UUID.CombID, max_length=32, primary_key=True, serialize=False)),
                ('prefer_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aurora_main.aurora_article_comment_model')),
                ('prefer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aurora_main.aurora_user_model')),
            ],
            options={
                'db_table': 'aurora_m2m_prefer_comment',
            },
        ),
        migrations.CreateModel(
            name='Aurora_M2M_Prefer_Article_Model',
            fields=[
                ('comb', models.CharField(default=aurora_etc.comb.Aurora_Comb_UUID.CombID, max_length=32, primary_key=True, serialize=False)),
                ('prefer_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aurora_main.aurora_article_model')),
                ('prefer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aurora_main.aurora_user_model')),
            ],
            options={
                'db_table': 'aurora_m2m_prefer_article',
            },
        ),
        migrations.CreateModel(
            name='Aurora_M2M_Group_Admin_User_Model',
            fields=[
                ('comb', models.CharField(default=aurora_etc.comb.Aurora_Comb_UUID.CombID, max_length=32, primary_key=True, serialize=False)),
                ('admin_type', models.CharField(default='管理员', max_length=32)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_user', to='aurora_main.aurora_user_model')),
                ('with_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_user_with_group', to='aurora_main.aurora_group_model')),
            ],
            options={
                'db_table': 'aurora_group_admin_user',
            },
        ),
        migrations.AddField(
            model_name='aurora_m2m_article_summary_model',
            name='m2m_summary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aurora_main.aurora_summary_model'),
        ),
        migrations.CreateModel(
            name='Aurora_M2M_Apply_Log_Model',
            fields=[
                ('comb', models.CharField(default=aurora_etc.comb.Aurora_Comb_UUID.CombID, max_length=32, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=500)),
                ('m2m_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_with_group', to='aurora_main.aurora_group_model')),
                ('m2m_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_with_user', to='aurora_main.aurora_user_model')),
            ],
            options={
                'db_table': 'aurora_user_group_apply',
            },
        ),
        migrations.CreateModel(
            name='Aurora_M2M_Admin_Log_Model',
            fields=[
                ('comb', models.CharField(default=aurora_etc.comb.Aurora_Comb_UUID.CombID, max_length=32, primary_key=True, serialize=False)),
                ('operation', models.CharField(max_length=10)),
                ('content', models.CharField(max_length=500)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_log_user', to='aurora_main.aurora_user_model')),
                ('with_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_with_group', to='aurora_main.aurora_group_model')),
            ],
            options={
                'db_table': 'aurora_admin_log',
            },
        ),
        migrations.CreateModel(
            name='Aurora_Invitation',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('remark', models.CharField(default='', max_length=20)),
                ('mail', models.CharField(max_length=30, unique=True)),
                ('used_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aurora_main.aurora_user_model')),
            ],
            options={
                'db_table': 'aurora_invitation',
            },
        ),
        migrations.AddField(
            model_name='aurora_group_model',
            name='m2m_admin',
            field=models.ManyToManyField(through='aurora_main.Aurora_M2M_Group_Admin_User_Model', to='aurora_main.Aurora_User_Model'),
        ),
        migrations.AddField(
            model_name='aurora_article_model',
            name='article_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='f_author', to='aurora_main.aurora_user_model'),
        ),
        migrations.AddField(
            model_name='aurora_article_model',
            name='article_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aurora_main.aurora_group_model'),
        ),
        migrations.AddField(
            model_name='aurora_article_model',
            name='article_origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aurora_main.aurora_article_model'),
        ),
        migrations.AddField(
            model_name='aurora_article_model',
            name='m2m_prefer',
            field=models.ManyToManyField(related_name='f_prefer_author', through='aurora_main.Aurora_M2M_Prefer_Article_Model', to='aurora_main.Aurora_User_Model'),
        ),
        migrations.AddField(
            model_name='aurora_article_comment_model',
            name='comment_article',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='aurora_main.aurora_article_model'),
        ),
        migrations.AddField(
            model_name='aurora_article_comment_model',
            name='comment_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aurora_main.aurora_user_model'),
        ),
        migrations.AddField(
            model_name='aurora_article_comment_model',
            name='reply_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aurora_main.aurora_article_comment_model'),
        ),
    ]
