# Generated by Django 3.2.12 on 2022-07-17 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aurora_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aurora_article_model',
            options={'ordering': ['-article_create_time']},
        ),
        migrations.RemoveField(
            model_name='aurora_article_model',
            name='article_last_update_time',
        ),
        migrations.RemoveField(
            model_name='aurora_summary_model',
            name='summary_is_private',
        ),
        migrations.AddField(
            model_name='aurora_article_comment_model',
            name='comment_img',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aurora_article_info_model',
            name='article_last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='aurora_invitation',
            name='mail',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='aurora_m2m_article_summary_model',
            name='m2m_article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aurora_main.aurora_article_model'),
        ),
        migrations.AlterField(
            model_name='aurora_m2m_user_follow_summary_model',
            name='m2m_summary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aurora_main.aurora_summary_model'),
        ),
        migrations.AlterField(
            model_name='aurora_m2m_user_group_model',
            name='m2m_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aurora_main.aurora_group_model'),
        ),
    ]
